import AsyncLock from "async-lock";
import TaskBase from "./TaskBase";
import MBTiles from "@mapbox/mbtiles";
import stream from "stream"
import fs from 'fs';
import { dialog } from "electron";
import path from "path";
import FileTask from "./FileTask";

const asyncLock = new AsyncLock();

export default class MBTilesTask extends TaskBase {
    constructor(task) {
        super(task);
        var _this = this;
        this._mbtiles = null;
        new MBTiles(this.path.replaceAll("\\", "/"), function (err, mbtiles) {
            if (err) {
                console.log(err)
                console.log(_this.path)
                task.enable = false;
            }
            _this._mbtiles = mbtiles;
        })
    }

    setEnable(val) {
        var result = false;
        if (val) {
            try {
                console.log(this._mbtiles)
                fs.accessSync(this.path, fs.constants.F_OK);
                result = this._mbtiles != null;
            } catch (error) {
                result = false;
            }
        }
        this.enable = result;
        return this.enable;
    }

    /**
     * 
     * @param {http.IncomingMessage} req 
     * @param {http.ServerResponse} res 
     * @param {TaskBase} task
     * @param {fs.Stats} stats
     */
    static async Action(req, res, task, stats) {
        asyncLock.acquire('fileTask-size-write', function () {
            ++task.useData
        })
        if (req.url.split('/').pop() === "getMap") {
            MBTilesTask.GetMapTemplete(req, res, task)
            return;
        } else if (req.url.split('/')[2] === 'static') {
            var task = {};
            task.path = path.join(__static, req.url.split('/').slice(3).join('/'));
            task.gzip = true;
            task.useData = 0;
            FileTask.Action(req, res, task)
            return;
        }
        MBTilesTask.GetTileRESTFul(req, res, task)
    }

    static GetMapTemplete(req, res, task) {
        task._mbtiles.getInfo(function (err, info) {
            var center = info.center;
            var minzoom = info.minzoom
            var maxzoom = info.maxzoom
            var htmlTemplete = `
<!DOCTYPE html>
<html>
<head>
  <title>Map Preview</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="static/lib/leaflet/leaflet.css"/>
  <script src="static/lib/leaflet/leaflet.js"></script>
  <style type="text/css">
    body {
       margin: 0;
       padding: 0;
    }
    html, body, #map{
       width: 100%;
       height: 100%;
    }
  </style>
</head>
<body>
  <div id="map"></div>
  <script>
      var map = L.map('map').setView([${center[1]}, ${center[0]}], ${center[2]});
      L.tileLayer('http://127.0.0.1:${req.headers.host.split(':').pop()}/${task.id}/{z}/{x}/{y}.png', {
        minZoom: ${minzoom},
        maxZoom: ${maxzoom},
        tms: false,
        attribution: 'Generated by WebPublish'
      }).addTo(map);
  </script>
</body>
</html>
        `
            res.end(htmlTemplete)
        })
    }

    /**
     * 
     * @param {*} req 
     * @param {http.ServerResponse} res 
     */
    static GetTileRESTFul(req, res, task) {
        var urlParam1 = req.url.split('.')
        var urlParam2 = urlParam1[0].split('/')
        var ext = urlParam1[1] || 'png'
        var z = urlParam2[2],
            x = urlParam2[3],
            y = urlParam2[4]

        task._mbtiles.getTile(z, x, y, function (err, data, headers) {
            if (err) {
                res.statusCode = 404;
                res.setHeader('Content-Type', 'text/javascript;charset=UTF-8');//utf8编码，防止中文乱码
                res.end("Tile rendering error: " + err)
                return;
            }
            res.setHeader('Content-Type', headers ? headers['Content-Type'] : "image/png")
            res.setHeader('Access-Control-Allow-Origin', "*")
            const bufferStream = new stream.PassThrough();
            bufferStream.end(data)
            bufferStream.pipe(res)
        })
    }

    Action(req, res, stats) {
        return MBTilesTask.Action(req, res, this, stats)
    }

    getUrl() {
        return '{z}/{x}/{y}.png'
    }
}