name: Build WebPublish For Win/Mac/Linux

# trigger
on:
  push:
    tags:
      - "v*"

# jobs
jobs:
  release:
    name: build and release WebPublish

    # type of machine to run the job on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest"]

    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@v2

      # step2: install node env
      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 12.21.0

      # step3: Npm install
      - name: npm install
        run: |
          npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # step4: build app
      - name: build app
        run: |
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # step5: cleanup artifacts in build
      - name: cleanup artifacts windows
        if: startsWith(matrix.os,'windows')
        run: |
          mv ./build/latest.yml ./
          npx rimraf "build/!(*.exe)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cleanup artifacts macos
        if: startsWith(matrix.os,'macos')
        run: |
          npx rimraf "build/!(*.dmg)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cleanup artifacts ubuntu
        if: startsWith(matrix.os,'ubuntu')
        run: |
          npx rimraf "build/!(*.deb)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # step6: upload artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }}
          path: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # step7: create release
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "build/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # step8: push to oss
      - name: init oss env
        if: startsWith(matrix.os,'windows')
        uses: yizhoumo/setup-ossutil@v1.0.2
        with:
          endpoint: "oss-cn-beijing.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
      
      - name: push to oss
        if: startsWith(matrix.os,'windows')
        run: |
          mv ./latest.yml ./build/
          ossutil cp -rf ./build/ oss://oss-ts/update/webpublish/
